### PR TITLE
IPAdapterLoadEmbeds  FIX LOAD Embeds

### PR DESCRIPTION
**Pull request by madtunebk**

### CODE REVIEW

**Comment by cubiq** [comment]
what is there to fix? current implementation saves in output and load from input (same as save latents)

**Comment by madtunebk** [comment]
If you look carefully, when you declare the input folder using folder_paths.get_input_directory(), you save it in folder_paths.get_input_directory(). Even if you manually copy the embeds from the output to the input folder, it won't detect any 'ipadapter' embeddings.

**Comment by cubiq** [comment]
I'm sorry I don't think I can replicate
image

**Comment by madtunebk** [comment]
I noticed that I also need to copy only files that end with '.ipadpt' from the output folder to the input folder, rather than copying the entire folder. This pull request can be closed. Apologies for the inconvenience and thank you for your time.

**Comment by cubiq** [comment]
thank you for looking into this!

**Pull request closed without merging**
